import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { BetProvider } from "./providers/BetContext";
import { AuthProvider } from "./providers/AuthContext";
import Navigation from "./components/Navigation";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="sq">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <AuthProvider>
          <BetProvider>
            <Navigation />
            {children}
          </BetProvider>
        </AuthProvider>
      </body>
    </html>
  );
}
